services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: $RABBIT_USER
      RABBITMQ_DEFAULT_PASS: $RABBIT_PASS
    volumes:
      - rabbitqm_data:/var/lib/rabbitmq

  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile.bot
    container_name: bot_container
    command: >
      sh -c "/wait-for-it.sh rabbit:5672 --timeout=60 --strict
      && /wait-for-it.sh postgres:5432 --timeout=60 --strict
      && python -m tg_bot.main"
    depends_on:
      - postgres
      - rabbit
    volumes:
      - .:/usr/bot

  main:
    build:
      context: .
      dockerfile: docker/main/Dockerfile.main
    container_name: main_container
    depends_on:
      - postgres
      - rabbit
      - bot
    volumes:
      - .:/usr/main
  
volumes:
  rabbitqm_data:
  postgres_data: