services:
  postgres:
    image: postgres:16.9-alpine3.22
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile.bot
    container_name: bot_container
    depends_on:
      - postgres
    volumes:
      - ./src/bot:/vct_notifications/src/bot
      - ./src/db:/vct_notifications/src/db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      BOT_TOKEN: $BOT_TOKEN


  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.app
    container_name: app_container
    depends_on:
      - postgres
      - bot
    volumes:
      - ./src/app:/vct_notifications/src/app
      - ./src/db:/vct_notifications/src/db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      BOT_TOKEN: $BOT_TOKEN
volumes:
  postgres_data: